const EErrors = {
	ROUTING_ERROR: 1,
	INVALID_TYPES_ERROR: 2,
	DATABASE_ERROR: 3,
	PRODUCT_NOT_FOUND: 4,
	PRODUCT_OUT_OF_STOCK: 5,
	PRODUCT_VALIDATION_ERROR: 6,
	CART_NOT_FOUND: 7,
	PRODUCT_NOT_IN_CART: 8,
	CART_VALIDATION_ERROR: 9,
	AUTHENTICATION_ERROR: 10,
	AUTHORIZATION_ERROR: 11,
	MESSAGE_NOT_FOUND: 12,
	MESSAGE_VALIDATION_ERROR: 13,
	TICKET_NOT_FOUND: 14,
	TICKET_VALIDATION_ERROR: 15,
	USER_NOT_FOUND: 16,
	USER_VALIDATION_ERROR: 17,
	USER_ALREADY_EXISTS: 18,
	INVALID_CREDENTIALS: 19,
	UNAUTHORIZED_ACTION: 20,
};

export default EErrors;
